### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by cloud-strife7777** [LightningMods/Itemzflow-Languages#20]
I have 04 German File. Which folder must this File???!

**Comment by LightningMods** [comment]
https://github.com/LightningMods/Itemzflow-Languages/blob/main/4/lang.ini

**Comment by cloud-strife7777** [comment]
Which folder must this File?

**Comment by LightningMods** [comment]
the one I linked, folder "4"

**Comment by cloud-strife7777** [comment]
In which path???

**Comment by cloud-strife7777** [comment]
???

**Comment by LightningMods** [comment]
[4/lang.ini](https://github.com/LightningMods/Itemzflow-Languages/blob/main/4/lang.ini)
that file goes in the folder "4" now stop replying to this closed issue
